FROM openjdk:11 As BUILD_CODE
LABEL "Project"="vprofile"
LABEL "Author"="vivek"
RUN apt-get update && apt-get install maven -y
RUN git clone https://github.com/vivek891011/vprofile-project.git
RUN cd vprofile-project && git checkout docker && mvn install -y

FROM tomcat:9-jre11
RUN rm -rf /usr/local/tomcat/webapps/*
CPOY --from=BUILD_IMAGE vprofile-project/target/vprofile-v2.war  /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]